<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T97_saldoawal_model extends CI_Model
{

    public $table = 't97_saldoawal';
    public $id = 'idsa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database($this->session->userdata('dbName'), true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        // $this->db->like('idsa', $q);
    	// $this->db->or_like('idakun', $q);
    	// $this->db->or_like('Debit', $q);
    	// $this->db->or_like('Kredit', $q);
    	// $this->db->or_like('idusers', $q);
    	// $this->db->or_like('created_at', $q);
    	// $this->db->or_like('updated_at', $q);
    	// $this->db->from($this->table);
        $this->db->like('t98_akun.Kode', $q);
        $this->db->or_like('t98_akun.Nama', $q);
        $this->db->select($this->table . '.*, t98_akun.Kode, t98_akun.Nama');
        $this->db->from($this->table);
        $this->db->join('t98_akun', 't98_akun.idakun = '.$this->table.'.idakun');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // $this->db->order_by($this->id, $this->order);
        $this->db->order_by('t98_akun.Kode', 'asc');
        // $this->db->like('idsa', $q);
    	// $this->db->or_like('idakun', $q);
    	// $this->db->or_like('Debit', $q);
    	// $this->db->or_like('Kredit', $q);
    	// $this->db->or_like('idusers', $q);
    	// $this->db->or_like('created_at', $q);
    	// $this->db->or_like('updated_at', $q);
        $this->db->like('t98_akun.Kode', $q);
        $this->db->or_like('t98_akun.Nama', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t98_akun.Kode, t98_akun.Nama');
        $this->db->from($this->table);
        $this->db->join('t98_akun', 't98_akun.idakun = '.$this->table.'.idakun');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // ambil nilai total
    function getTotal()
    {
        $this->db->select_sum('Debit');
        $this->db->select_sum('Kredit');
        return $this->db->get($this->table)->row();
    }

}

/* End of file T97_saldoawal_model.php */
/* Location: ./application/models/T97_saldoawal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-24 19:22:21 */
/* http://harviacode.com */
