<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T02_tamu_model extends CI_Model
{

    public $table = 't02_tamu';
    public $id = 'idtamu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database('TAMU', true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtamu', $q);
		$this->db->or_like('TripNo', $q);
		$this->db->or_like('TripTgl', $q);
		$this->db->or_like('Nama', $q);
		$this->db->or_like('MFC', $q);
		$this->db->or_like('Country', $q);
		$this->db->or_like('PackageNight', $q);
		$this->db->or_like('PackageType', $q);
		$this->db->or_like('CheckIn', $q);
		$this->db->or_like('CheckOut', $q);
		$this->db->or_like('Agent', $q);
		$this->db->or_like('Status', $q);
		$this->db->or_like('DaysStay', $q);
		$this->db->or_like('Price', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtamu', $q);
		$this->db->or_like('TripNo', $q);
		$this->db->or_like('TripTgl', $q);
		$this->db->or_like('Nama', $q);
		$this->db->or_like('MFC', $q);
		$this->db->or_like('Country', $q);
		$this->db->or_like('PackageNight', $q);
		$this->db->or_like('PackageType', $q);
		$this->db->or_like('CheckIn', $q);
		$this->db->or_like('CheckOut', $q);
		$this->db->or_like('Agent', $q);
		$this->db->or_like('Status', $q);
		$this->db->or_like('DaysStay', $q);
		$this->db->or_like('Price', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    /**
     * modif function insert, untuk save hasil import
     */
    function insert_import($data)
    {
        $this->db->insert_batch($this->table, $data);
    }

    /**
     * untuk combo pada menu tamu - pembayaran
     */
    function getData($q)
    {
        $q = "
            select
                *
            from
                (select
                    *
                from
                    t02_tamu
                where
                    TripNo not in (select TripNo from t03_bayar)
                ) a
            where
                TripNo like '%".$q."%'
            group by
                TripNo
            order by
                TripNo
        ";
        return $this->db->query($q)->result();
    }

    // get data by TripNo
    function getByTripNo($TripNo)
    {
        $this->db->where('TripNo', $TripNo);
        return $this->db->get($this->table)->row();
    }

    // get all data by TripNo
    function getAllByTripNo($TripNo)
    {
        $this->db->where('TripNo', $TripNo);
        return $this->db->get($this->table)->result();
    }

}

/* End of file T02_tamu_model.php */
/* Location: ./application/models/T02_tamu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-02 18:17:50 */
/* http://harviacode.com */
