<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T30_tamu_model extends CI_Model
{

    public $table = 't30_tamu';
    public $id = 'idtamu';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database('TAMU', true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtamu', $q);
		$this->db->or_like('TripNo', $q);
		$this->db->or_like('TripTgl', $q);
		$this->db->or_like('Name', $q);
		$this->db->or_like('PackageName', $q);
		$this->db->or_like('Night', $q);
		$this->db->or_like('CheckIn', $q);
		$this->db->or_like('CheckOut', $q);
		$this->db->or_like('Agent', $q);
		$this->db->or_like('PriceList', $q);
		$this->db->or_like('FeeTanas', $q);
		$this->db->or_like('PricePay', $q);
		$this->db->or_like('Remarks', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtamu', $q);
		$this->db->or_like('TripNo', $q);
		$this->db->or_like('TripTgl', $q);
		$this->db->or_like('Name', $q);
		$this->db->or_like('PackageName', $q);
		$this->db->or_like('Night', $q);
		$this->db->or_like('CheckIn', $q);
		$this->db->or_like('CheckOut', $q);
		$this->db->or_like('Agent', $q);
		$this->db->or_like('PriceList', $q);
		$this->db->or_like('FeeTanas', $q);
		$this->db->or_like('PricePay', $q);
		$this->db->or_like('Remarks', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // ambil idtamu
    function getInsertId()
    {
        return $this->db->insert_id();
    }

    // get data by trip no.
    function get_by_TripNo($TripNo)
    {
        $this->db->where('TripNo', $TripNo);
        return $this->db->get($this->table)->row();
    }

    /**
     * hapus data berdasarkan Trip No.
     */
    function deleteTripNo($TripNo)
    {
        $q = "
            delete
            from
                t30_tamu
            where
                TripNo = '".$TripNo."'
        ";
        $this->db->query($q);
    }

}

/* End of file T30_tamu_model.php */
/* Location: ./application/models/T30_tamu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-12 17:27:06 */
/* http://harviacode.com */
