<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T31_bayar_model extends CI_Model
{

    public $table = 't31_bayar';
    public $id = 'idbayar';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database('TAMU', true);
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('t30_tamu.Name');
        $this->db->or_like('t30_tamu.TripNo');
        $this->db->or_like('t30_tamu.TripTgl');
        $this->db->select($this->table.'.*');
        $this->db->from($this->table);
        $this->db->join('t30_tamu', 't30_tamu.idtamu = '.$this->table.'.idtamu');
        // $this->db->join('t32_bayard', 't32_bayard.idbayar = '.$this->table.'.idbayar');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('t30_tamu.Name');
        $this->db->or_like('t30_tamu.TripNo');
        $this->db->or_like('t30_tamu.TripTgl');
		$this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select('t30_tamu.TripNo, t30_tamu.TripTgl, t30_tamu.Name');
        $this->db->from($this->table);
        $this->db->join('t30_tamu', 't30_tamu.idtamu = '.$this->table.'.idtamu');
        return $this->db->get()->result();
    }

    /**
     * ambil data tamu sesuai trip plus data detail pembayaran
     */
    // function get_limit_data_bayard($limit, $start = 0, $q = NULL) {
    function get_limit_data_bayard($q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('t30_tamu.Name');
        $this->db->or_like('t30_tamu.TripNo');
        $this->db->or_like('t30_tamu.TripTgl');
        $this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select('t30_tamu.TripNo, t30_tamu.TripTgl, t30_tamu.Name');
        $this->db->select('t32_bayard.idtop, t32_bayard.Jumlah, concat(t32_bayard.idbayar, t32_bayard.idtop) as idbayar_idtop');
        $this->db->from($this->table);
        $this->db->join('t30_tamu', 't30_tamu.idtamu = '.$this->table.'.idtamu');
        $this->db->join('t32_bayard', 't32_bayard.idbayar = '.$this->table.'.idbayar');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // ambil idbayar
    function getInsertId()
    {
        return $this->db->insert_id();
    }

    /**
     * hapus data berdasarkan Trip No.
     */
    function deleteTripNo($TripNo)
    {
        $q = "
            delete
            from
                t31_bayar
            where
                idtamu in (select idtamu from t30_tamu where TripNo = '".$TripNo."')
        ";
        $this->db->query($q);
    }

}

/* End of file T31_bayar_model.php */
/* Location: ./application/models/T31_bayar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-10 20:14:46 */
/* http://harviacode.com */
